### ISSUE TITLE
Rebase kubespray to use a fork of the upstream kubespray repo

### ISSUE THREAD

**Issue by spisarski** [cablelabs/snaps-kubernetes#157]
Use our cablelabs kubespray fork rather than Aricent's Kubernetes_Kubespray repo tarball

**Comment by sbhojpur** [comment]
@spisarski:  I got a chance to review the code and the changes looks OK to me. Here are some of the minor things that we can do along with these changes

Modify  function 'def __manage_keys(config)' to include Docker_Repo node as well.  It could be some server other then k8s_cluster nodes

Also i think we should rename the key 'registry_port' in k8s-deploy.yaml to 'docker_url_port', it gives it a more meaningful name.

Also should we use coredns instead of kube-dns , i guess it is already supported in K8 1.12 and there is parameter for this in k8s_cluster.yaml


Br.
Sachin

**Comment by spisarski** [comment]
Currently testing with kubespray fork PR https://github.com/cablelabs/kubespray/pull/1

**Comment by spisarski** [comment]
@sbhojpur, thanks for your review. 

#1 Adding to next push
#2 Created issue https://github.com/cablelabs/snaps-kubernetes/issues/163
#3 CoreDNS is currently being used

**Comment by spisarski** [comment]
PR merged
