### ISSUE TITLE
certificate issue during deployment

### ISSUE THREAD

**Issue by bo-quan** [cablelabs/snaps-kubernetes#173]
One customer ran into the following certificate issue during deployment:

Applying playbook [/home/ubuntu/snaps-kubernetes/snaps_k8s/playbooks/k8/k8_node_label.yaml] with variables - {'PROJ_ARTIFACT_DIR': '/tmp/snaps-k8s-projects/Kubernetes', 'hostname': 'master', 'label_value': 'master', 'label_key': 'zone'}
 
PLAY [localhost] *******************************************************************************************************************************************************************************
 
TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [localhost]
 
TASK [kubectl label nodes master zone-] ********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "--kubeconfig=/tmp/snaps-k8s-projects/Kubernetes/node-kubeconfig.yaml", "label", "nodes", "master", "zone-"], "delta": "0:00:00.068198", "end": "2019-01-29 14:00:03.249224", "msg": "non-zero return code", "rc": 1, "start": "2019-01-29 14:00:03.181026", "stderr": "Unable to connect to the server: x509: certificate is valid for 10.130.0.22, 10.241.241.1, 127.0.0.1, not 10.46.201.22", "stderr_lines": ["Unable to connect to the server: x509: certificate is valid for 10.130.0.22, 10.241.241.1, 127.0.0.1, not 10.46.201.22"], "stdout": "", "stdout_lines": []}
...ignoring
 
TASK [kubectl label nodes master zone=master] **************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["kubectl", "--kubeconfig=/tmp/snaps-k8s-projects/Kubernetes/node-kubeconfig.yaml", "label", "nodes", "master", "zone=master"], "delta": "0:00:00.086294", "end": "2019-01-29 14:00:03.495323", "msg": "non-zero return code", "rc": 1, "start": "2019-01-29 14:00:03.409029", "stderr": "Unable to connect to the server: x509: certificate is valid for 10.130.0.22, 10.241.241.1, 127.0.0.1, not 10.46.201.22", "stderr_lines": ["Unable to connect to the server: x509: certificate is valid for 10.130.0.22, 10.241.241.1, 127.0.0.1, not 10.46.201.22"], "stdout": "", "stdout_lines": []}
[WARNING]: Could not create retry file '/home/ubuntu/snaps-kubernetes/snaps_k8s/playbooks/k8/k8_node_label.retry'.         [Errno 13] Permission denied: '/home/ubuntu/snaps-
kubernetes/snaps_k8s/playbooks/k8/k8_node_label.retry'
 
PLAY RECAP *************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1  
 
Traceback (most recent call last):
  File "/home/ubuntu/snaps-kubernetes/iaas_launch.py", line 163, in <module>
    run(args)
  File "/home/ubuntu/snaps-kubernetes/iaas_launch.py", line 131, in run
    k8_utils.execute(config)
  File "/home/ubuntu/snaps-kubernetes/snaps_k8s/provision/k8_utils.py", line 32, in execute
    __install_k8s(k8s_conf)
  File "/home/ubuntu/snaps-kubernetes/snaps_k8s/provision/k8_utils.py", line 43, in __install_k8s
    aconf.start_k8s_install(k8s_conf)
  File "/home/ubuntu/snaps-kubernetes/snaps_k8s/provision/ansible_configuration.py", line 99, in start_k8s_install
    __complete_k8s_install(k8s_conf, base_pb_vars)
  File "/home/ubuntu/snaps-kubernetes/snaps_k8s/provision/ansible_configuration.py", line 768, in __complete_k8s_install
    __label_nodes(k8s_conf)
  File "/home/ubuntu/snaps-kubernetes/snaps_k8s/provision/ansible_configuration.py", line 846, in __label_nodes
    consts.K8_NODE_LABELING, variables=pb_vars)
  File "/usr/local/lib/python2.7/dist-packages/snaps_common/ansible_snaps/ansible_utils.py", line 143, in apply_playbook
    playbook_path, ret_val, connection))
snaps_common.ansible_snaps.ansible_utils.AnsibleException: Error applying playbook [/home/ubuntu/snaps-kubernetes/snaps_k8s/playbooks/k8/k8_node_label.yaml] with value [2] using the connection type of [local]

**Comment by chiraggupta06** [comment]
Hi,

Unable to connect to the server: x509: certificate is valid for 10.130.0.22, 10.241.241.1, 127.0.0.1, not 10.46.201.22", "stderr_lines": ["Unable to connect to the server: x509: certificate is valid for 10.130.0.22, 10.241.241.1, 127.0.0.1, not 10.46.201.22"], "stdout": "", "stdout_lines": []}

It seems that node-master.pem certificate has an extra IP ‘10.46.201.22’
It could be because default routes in your machine are on an IP different from the IP you wish to use for K8s management plane.

Can you please share your—
k8s_deploy. Yaml

The output of the following command on the master node.
>route -n 
>ip a

Regards,
Chirag Gupta

**Comment by spisarski** [comment]
@chiraggupta06 - Thank you for checking and here is the config.
[casa_k8s.zip](https://github.com/cablelabs/snaps-kubernetes/files/2832703/casa_k8s.zip)

**Comment by bo-quan** [comment]
@chiraggupta06 The customer repurposed the servers so we'll have to wait a bit till he tries to reproduce it.  Looking at the k8s deployment yaml file Steve sent, can you point out something that we probably want to change to avoid the error when he tries to do it again?

**Comment by chiraggupta06** [comment]
HI @bo-quan ,

From deployment.yaml, we are suspecting that User has used management IP(10.46.201.22) instead of the data IP(10.130.0.22, for which default gateway is set) in k8s_deploy.yaml.
Kubespray creates the certificates by using data IP thus it's  giving an error "Unable to connect to the server: x509: certificate is valid for 10.130.0.22, 10.241.241.1, 127.0.0.1, not 10.46.201.22", "stderr_lines": ["Unable to connect to the server: x509: certificate is valid for 10.130.0.22, 10.241.241.1, 127.0.0.1, not 10.46.201.22"], "stdout": "", "stdout_lines": []}" as management IP(10.46.201.22) is not present in the certificates.

To confirm, we would need the certificate and the output of the mentioned commands.

Thanks.
