### ISSUE TITLE
Submit CNCF 1.13.3 validation results for certification

### ISSUE THREAD

**Issue by spisarski** [cablelabs/snaps-kubernetes#178]
After the issue-157 branch is merged into master, run and submit the CNCF certification tests

**Comment by chriscorcimiglia** [comment]
Here is some additional information for working this issue:

1. Instructions from K8s Conformance https://github.com/cncf/k8s-conformance/blob/master/instructions.md
1. The successful v1.11 PR from Sanjhana https://github.com/cncf/k8s-conformance/pull/376/files
1. The snaps-k8s CI readme (since the test can be executed as part of CI) https://github.com/cablelabs/snaps-kubernetes/tree/master/ci
1. The `conformance.yaml` playbook that should be used for executing the tests https://github.com/cablelabs/snaps-kubernetes/blob/master/ci/playbooks/conformance.yaml and producing the files required for the submission PR

**Comment by RandyLevensalor** [comment]
https://github.com/cncf/k8s-conformance/pull/639
