### ISSUE TITLE
Move to overlay2 docker storage driver

### ISSUE THREAD

**Issue by RandyLevensalor** [cablelabs/snaps-kubernetes#83]
Overlay2 is preferred over aufs.
https://docs.docker.com/storage/storagedriver/overlayfs-driver/#configure-docker-with-the-overlay-or-overlay2-storage-driver

**Comment by sytech-git** [comment]
Out-of-the-box Ubuntu distro version - UB16.04 LTS uses the following Linux kernel version that support the listed Docker Engine Storage Drivers:

Linux kernel 4.4.0-xxx
Docker Storage Drivers: AUFS, OVERLAY_V1, OVERLAY_V2

Either after performing an update to the entire UB16.04LTS distro or just updating the Linux kernel (for feature update, security vulnerability, bug fix etc) one can end up with the following Linux kernel versions that ONLY support OVERLAY_V2 for Docker Engine as the Storage Driver:
 
Linux kernel 4.10.10-xxx
OVERLAY_V2

Linux kernel 4.14.10-xxx
OVERLAY_V2

Docker Engine Community Editions as listed below are configured by default to use AUFS Storage Driver:
Docker Engine 18.xx.x-ce
AUFS

Docker Engine 17.xx.x-ce
AUFS

If upon system start time, Docker Engine is initialized it will fail to run since the newer Linux kernel version do NOT support AUFS Storage Driver any more. This in turn shall prevent K8s server to instantiate pods. 

Workaround:
A minor change shall have to be made to the installation script for Docker Engine so that K8s server is not effected.

On Docker CE any version with newer Ubuntu Linux kernel after 4.4.0-xxx perform the following:

/etc/systemd/system/docker.service
ADD this below:
ExecStart= -s overlay2

systemctl stop docker
systemctl daemon-reload
systemctl start docker

**Comment by chriscorcimiglia** [comment]
Fixed by #102
