### ISSUE TITLE
Cleanup -k8_c option does not work

### ISSUE THREAD

**Issue by spisarski** [cablelabs/snaps-kubernetes#88]
Following error is raised:
IOError: [Errno 2] No such file or directory: '/home/spisarski/git/snaps-kubernetes/snaps_k8s/projects/project_name/deployment_bkup.yaml'

**Comment by spisarski** [comment]
Tried to reinstall after a -k8_c and -k8_d failed trying to restart docker. It seems like the cleanup routine is leaving around artifacts.

**Comment by spisarski** [comment]
Observed that the deployment_bkup.yaml file is not getting created when not using the -f filename deployment.yaml. The -f option should take in any filename.

**Comment by chiraggupta06** [comment]
HI Steven,

1. Following error is raised:
IOError: [Errno 2] No such file or directory: '/home/spisarski/git/snaps-kubernetes/snaps_k8s/projects/project_name/deployment_bkup.yaml'

deployment_bkup.yaml file gets created at the time of successful deployment of kubernetes and it used at the time of cluster cleanup. Can you check whether the deployment was successful before attempting the cleanup?

2. From last run pb k8_clean_up.yaml

TASK [Reset/Remove kubernet cluster|logs redirect to /var/log/kubernetes_kubespray.log] ***********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "ansible-playbook -i inventory/sample/inventory.cfg -u root -e ansible_ssh_user=root -b reset.yml >>/var/log/kubernetes_kubespray.log", "delta": "0:00:27.140642", "end": "2018-08-10 20:24:25.786365", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2018-08-10 20:23:58.645723", "stderr": " [WARNING]: Not prompting as we are not in interactive mode\n [WARNING]: Could not match supplied host pattern, ignoring: vault\n [WARNING]: Could not match supplied host pattern, ignoring: calico-rr\n [WARNING]: Consider using mount module rather than running mount", "stderr_lines": [" [WARNING]: Not prompting as we are not in interactive mode", " [WARNING]: Could not match supplied host pattern, ignoring: vault", " [WARNING]: Could not match supplied host pattern, ignoring: calico-rr", " [WARNING]: Consider using mount module rather than running mount"], "stdout": "", "stdout_lines": []}
to retry, use: --limit @/home/spisarski/git/snaps-kubernetes/snaps_k8s/ansible_p/commission/kubernetes/playbooks/deploy_mode/k8/k8_clean_up.retry

PLAY RECAP ****************************************************************************************************************
localhost : ok=7 changed=2 unreachable=0 failed=1


Also, if possible can you share the logs of /var/log/kubernetes_kubespray.log file

Thanks.

Regards,
Chirag Gupta
